#!/bin/bash


WORKING_DIR=$(pwd)
SCRIPT_DIR=$(dirname -- $(readlink -f "$0"))

mkdir $WORKING_DIR/src
mkdir $WORKING_DIR/incl
cp $SCRIPT_DIR/Makefile-base Makefile


touch $WORKING_DIR/src/main.cpp
vim $WORKING_DIR/src/main.cpp

echo Done! Happy coding
